/********PENDIENTES A PASAR A PRODUCCION********/
Insert into dbo.TIPOPREGUNTA(IDTIPOPREGUNTA, NOMBRETIPOPREGUNTA) VALUES (3, 'Abierta extendida');
Insert into dbo.TIPOPREGUNTA(IDTIPOPREGUNTA, NOMBRETIPOPREGUNTA) VALUES (4, 'Selección Multiple');

CREATE TABLE TIPOPROCESO(
IDTIPOPROCESO INT PRIMARY KEY IDENTITY(1,1),
NOMBRETIPOPROCESO VARCHAR(50) NOT NULL
);

ALTER TABLE PROCESO
ADD IDTIPOPROCESO INT NULL;

ALTER TABLE PROCESO
ADD FOREIGN KEY (IDTIPOPROCESO) REFERENCES TIPOPROCESO(IDTIPOPROCESO);

ALTER TABLE MENOREDAD
DROP COLUMN PESOMENOREDAD;

ALTER TABLE MENOREDAD
DROP COLUMN TALLAMENOREDAD;

ALTER TABLE SOLUCIONCUESTIONARIO
ADD IDUSUARIOINGRESA INT NULL;

ALTER TABLE SOLUCIONCUESTIONARIO
ADD IDUSUARIOMODIFICA INT NULL;

ALTER TABLE SOLUCIONCUESTIONARIO
ADD FOREIGN KEY (IDUSUARIOINGRESA) REFERENCES USUARIO (IDUSUARIO);

ALTER TABLE SOLUCIONCUESTIONARIO
ADD FOREIGN KEY (IDUSUARIOMODIFICA) REFERENCES USUARIO (IDUSUARIO);

/********PASADOS A PRODUCCION********/