/********PENDIENTES A PASAR A PRODUCCION********/
Insert into dbo.TIPOPREGUNTA(IDTIPOPREGUNTA, NOMBRETIPOPREGUNTA) VALUES (3, 'Abierta extendida');
Insert into dbo.TIPOPREGUNTA(IDTIPOPREGUNTA, NOMBRETIPOPREGUNTA) VALUES (4, 'Selección Multiple');


/********PASADOS A PRODUCCION********/